// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { Result, AccountId32Like, AccountId32 } from "dedot/codecs";
import type {
  GenericContractQuery,
  GenericContractQueryCall,
  ContractCallOptions,
  GenericContractCallResult,
  ContractCallResult,
} from "dedot/contracts";
import type {
  StakingErrorsStakingError,
  InkPrimitivesLangError,
} from "./types";

export interface ContractQuery<ChainApi extends GenericSubstrateApi>
  extends GenericContractQuery<ChainApi> {
  /**
   *
   * @param {bigint} amount
   * @param {ContractCallOptions} options
   *
   * @selector 0x5adb38de
   **/
  stake: GenericContractQueryCall<
    ChainApi,
    (
      amount: bigint,
      options: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], StakingErrorsStakingError>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x82364901
   **/
  unstake: GenericContractQueryCall<
    ChainApi,
    (
      options: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Result<[], StakingErrorsStakingError>,
        ContractCallResult<ChainApi>
      >
    >
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x02c779a5
   **/
  getTotalStaked: GenericContractQueryCall<
    ChainApi,
    (
      options: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint, ContractCallResult<ChainApi>>
    >
  >;

  /**
   *
   * @param {AccountId32Like} user
   * @param {ContractCallOptions} options
   *
   * @selector 0x15ee10d6
   **/
  getBalanceByAccount: GenericContractQueryCall<
    ChainApi,
    (
      user: AccountId32Like,
      options: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<bigint, ContractCallResult<ChainApi>>
    >
  >;

  /**
   *
   * @param {ContractCallOptions} options
   *
   * @selector 0x0003a813
   **/
  getAllStakers: GenericContractQueryCall<
    ChainApi,
    (
      options: ContractCallOptions,
    ) => Promise<
      GenericContractCallResult<
        Array<AccountId32>,
        ContractCallResult<ChainApi>
      >
    >
  >;
}
