// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
} from "dedot/contracts";

export interface ContractTx<ChainApi extends GenericSubstrateApi>
  extends GenericContractTx<ChainApi> {
  /**
   *
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0x5adb38de
   **/
  stake: GenericContractTxCall<
    ChainApi,
    (
      amount: bigint,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x82364901
   **/
  unstake: GenericContractTxCall<
    ChainApi,
    (options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;
}
