// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
} from "dedot/contracts";

export interface ContractTx<ChainApi extends GenericSubstrateApi>
  extends GenericContractTx<ChainApi> {
  /**
   *
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0x5adb38de
   **/
  stake: GenericContractTxCall<
    ChainApi,
    (
      amount: bigint,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {bigint} amount
   * @param {ContractTxOptions} options
   *
   * @selector 0x410fcc9d
   **/
  withdraw: GenericContractTxCall<
    ChainApi,
    (
      amount: bigint,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x9a8353a7
   **/
  claimReward: GenericContractTxCall<
    ChainApi,
    (options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {bigint} period
   * @param {ContractTxOptions} options
   *
   * @selector 0x00a64005
   **/
  setLockTime: GenericContractTxCall<
    ChainApi,
    (
      period: bigint,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;
}
