// Generated by dedot cli

import type { AccountId32 } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type Staking = {
  data: StakingDataStakingData;
  tokenContract: AccountId32;
};

export type StakingDataStakingData = {
  stakingBalance: InkStorageLazyMapping;
  hasStaked: InkStorageLazyMapping;
  owner?: AccountId32 | undefined;
  stakers: Array<AccountId32>;
  totalStaked: bigint;
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type StakingErrorsStakingError =
  | { type: "Custom"; value: string }
  | { type: "OverFlow" }
  | { type: "NotApproved" }
  | { type: "TransferFail" }
  | { type: "LowLiquidity" };

export type InkEnvNoChainExtension = null;
