import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { Providers as UiProvider } from "@/providers/ChakraProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import WalletProvider from "@/providers/WalletProvider";
import ApiProvider from "@/providers/ApiProvider";
import MainFooter from "@/components/shared/MainFooter";
import MainHeader from "@/components/shared/MainHeader";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Stake Token",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <UiProvider>
          <WalletProvider>
            <ApiProvider>
              <MainHeader/>
              <ToastContainer />
              {children}
              <MainFooter/>
            </ApiProvider>
          </WalletProvider>
        </UiProvider>
      </body>
    </html>
  );
}
